export const FETCH_RANDOM_IMAGE_START = "FETCH_RANDOM_IMAGE_START";
export const FETCH_RANDOM_IMAGE_SUCCESS = "FETCH_RANDOM_IMAGE_SUCCESS";
export const FETCH_RANDOM_IMAGE_FAILED = "FETCH_RANDOM_IMAGE_FAILED";
export const CLEAR_IMAGE_STATE = "CLEAR_IMAGE_STATE";
